#!/bin/bash

run_script() {
    # First parameter is a suffix for the build type eg. test, dev
    SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
    pushd "$SCRIPT_DIR"

    mkdir -p ../../build/nsis
    cd ../../build/nsis
    source ../../ShellScripts/common/get_version.sh

    cp ../../installers/win32/* ./

    if ! curl -o OoliteReadMe.pdf -L https://oolite.readthedocs.io/en/latest/index.pdf; then
       echo "❌ OoliteReadMe.pdf (index.pdf) download failed!" >&2
       return 1
    fi
    if ! curl -o AdviceForNewCommanders.pdf -L https://oolite.readthedocs.io/en/latest/advice/advice.pdf; then
       echo "❌ AdviceForNewCommanders.pdf (advice.pdf) download failed!" >&2
       return 1
    fi
    if ! curl -o OoliteRS.pdf -L https://oolite.readthedocs.io/en/latest/reference/reference.pdf; then
       echo "❌ OoliteRS.pdf (reference.pdf) download failed!" >&2
       return 1
    fi
    if ! curl -o Privacy.pdf -L https://oolite.readthedocs.io/en/latest/privacy/privacy.pdf; then
       echo "❌ Privacy.pdf (privacy.pdf) download failed!" >&2
       return 1
    fi
    if ! curl -o License.pdf -L https://oolite.readthedocs.io/en/latest/license/license.pdf; then
       echo "❌ License.pdf (license.pdf) download failed!" >&2
       return 1
    fi

    # Passing arguments cause problems with some versions of NSIS.
    # Because of this, we generate them into a separate file and include them.
    echo "; Version Definitions for Oolite" > OoliteVersions.nsh
    echo "; NOTE - This file is auto-generated by the Makefile, any manual edits will be overwritten" >> OoliteVersions.nsh
    echo "!define VER_MAJ ${VER_MAJ}" >> OoliteVersions.nsh
    echo "!define VER_MIN ${VER_MIN}" >> OoliteVersions.nsh
    echo "!define VER_REV ${VER_REV}" >> OoliteVersions.nsh
    echo "!define VER_GITREV ${VER_GITREV}" >> OoliteVersions.nsh
    echo "!define VER_GITHASH ${VER_GITHASH}" >> OoliteVersions.nsh
    echo "!define VERSION ${VER}" >> OoliteVersions.nsh
    echo "!define BUILDTIME \"${BUILDTIME}\"" >> OoliteVersions.nsh
    echo "!define BUILDHOST_IS64BIT 1" >> OoliteVersions.nsh

    if [[ "$1" == "dev" ]]; then
        echo "!define SNAPSHOT 1" >> OoliteVersions.nsh
    elif [[ "$1" != "test" ]]; then
        echo "!define DEPLOYMENT 1" >> OoliteVersions.nsh
    fi

    if [[ -n "$MINGW_PREFIX" ]]; then
        NSIS=$MINGW_PREFIX/bin/makensis
    else
        NSIS=/nsis/makensis.exe
    fi
    if ! $NSIS -DOUTDIR="../" OOlite.nsi; then
        echo "❌ NSIS creation failed!" >&2
        return 1
    fi
    popd
}

run_script "$@"
status=$?


# Exit only if not sourced
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    exit $status
fi

