#!/bin/bash -x
#
# Creates the windows installer using NSIS.

create_nsis() {
    local build_folder="$1"  # Build folder
    local ver_full="$2"  # Oolite version
    local ver_gitrev="$3"  # Total number of commits in the history of current branch
    local ver_githash="$4"  # Git hash
    local buildtime="$5"  # Oolite build time
    local build_type="$6"  # Typically one of "test", "dev" or omitted for release builds

    local script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
    pushd "$script_dir"

    mkdir -p ../../build/nsis
    cd ../../build/nsis

    cp ../../installers/win32/* ./

    if ! curl -o OoliteReadMe.pdf -L https://oolite.readthedocs.io/en/latest/index.pdf; then
       echo "❌ OoliteReadMe.pdf (index.pdf) download failed!" >&2
       return 1
    fi
    if ! curl -o AdviceForNewCommanders.pdf -L https://oolite.readthedocs.io/en/latest/advice/advice.pdf; then
       echo "❌ AdviceForNewCommanders.pdf (advice.pdf) download failed!" >&2
       return 1
    fi
    if ! curl -o OoliteRS.pdf -L https://oolite.readthedocs.io/en/latest/reference/reference.pdf; then
       echo "❌ OoliteRS.pdf (reference.pdf) download failed!" >&2
       return 1
    fi
    if ! curl -o Privacy.pdf -L https://oolite.readthedocs.io/en/latest/privacy/privacy.pdf; then
       echo "❌ Privacy.pdf (privacy.pdf) download failed!" >&2
       return 1
    fi
    if ! curl -o License.pdf -L https://oolite.readthedocs.io/en/latest/license/license.pdf; then
       echo "❌ License.pdf (license.pdf) download failed!" >&2
       return 1
    fi

    local oolite_dir="../$build_folder"
    oolite_dir="${oolite_dir//\//\\}"


    [[ "$ver_full" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+).*\.([0-9]+)$ ]]  # Regex captures: Major, Minor, Patch, Distance
    local ver_maj="${BASH_REMATCH[1]}"
    local ver_min="${BASH_REMATCH[2]}"
    local ver_rev="${BASH_REMATCH[3]}"
    local ver_dist="${BASH_REMATCH[4]}"
    local ver_nsis="${ver_maj}.${ver_min}.${ver_rev}.${ver_dist}"

    # Passing arguments can cause problems with NSIS so we generate them into a separate file and include them.
    echo "; Version Definitions for Oolite" > OoliteVersions.nsh
    echo "; NOTE - This file is auto-generated by the Makefile, any manual edits will be overwritten" >> OoliteVersions.nsh
    echo "!define OOLITE_DIR ${oolite_dir}" >> OoliteVersions.nsh
    echo "!define VER_MAJ ${ver_maj}" >> OoliteVersions.nsh
    echo "!define VER_MIN ${ver_min}" >> OoliteVersions.nsh
    echo "!define VER_REV ${ver_rev}" >> OoliteVersions.nsh
    echo "!define VER_GITREV ${ver_gitrev}" >> OoliteVersions.nsh
    echo "!define VER_GITHASH ${ver_githash}" >> OoliteVersions.nsh
    echo "!define VERSION ${ver_nsis}" >> OoliteVersions.nsh
    echo "!define SEMVER ${ver_full}" >> OoliteVersions.nsh
    echo "!define BUILDTIME \"${buildtime}\"" >> OoliteVersions.nsh
    echo "!define BUILDHOST_IS64BIT 1" >> OoliteVersions.nsh

    if [[ "$build_type" == "dev" ]]; then
        echo "!define DEV_RELEASE 1" >> OoliteVersions.nsh
    elif [[ "$build_type" != "test" ]]; then
        echo "!define DEPLOYMENT_RELEASE 1" >> OoliteVersions.nsh
    fi

    local nsis
    if [[ -v MINGW_PREFIX ]]; then
        nsis=$MINGW_PREFIX/bin/makensis
    else
        nsis=/nsis/makensis.exe
    fi
    if ! $nsis -DOUTDIR="../" OOlite.nsi; then
        echo "❌ NSIS creation failed!" >&2
        return 1
    fi
    popd
}
