#!/bin/bash -x
#
# Creates the windows installer using NSIS.

create_nsis() {
    local build_type="$1"  # Typically one of "deployment", "test", "dev"
    local build_folder="$2"  # Build folder

    local script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
    pushd "$script_dir"
    source ../../ShellScripts/common/parse_manifest_fn.sh

    mkdir -p ../../build/nsis
    cd ../../build/nsis
    local oolite_dir="../$build_folder"
    local ver_full ver_quad ver_githash buildtime app_date
    parse_manifest ver_full ver_quad ver_githash buildtime app_date "$oolite_dir/Resources/manifest.plist"
    cp ../../installers/win32/* ./

    if ! curl -o OoliteReadMe.pdf -L https://oolite.readthedocs.io/en/latest/index.pdf; then
       echo "❌ OoliteReadMe.pdf (index.pdf) download failed!" >&2
       return 1
    fi
    if ! curl -o AdviceForNewCommanders.pdf -L https://oolite.readthedocs.io/en/latest/advice/advice.pdf; then
       echo "❌ AdviceForNewCommanders.pdf (advice.pdf) download failed!" >&2
       return 1
    fi
    if ! curl -o OoliteRS.pdf -L https://oolite.readthedocs.io/en/latest/reference/reference.pdf; then
       echo "❌ OoliteRS.pdf (reference.pdf) download failed!" >&2
       return 1
    fi
    if ! curl -o Privacy.pdf -L https://oolite.readthedocs.io/en/latest/privacy/privacy.pdf; then
       echo "❌ Privacy.pdf (privacy.pdf) download failed!" >&2
       return 1
    fi
    if ! curl -o License.pdf -L https://oolite.readthedocs.io/en/latest/license/license.pdf; then
       echo "❌ License.pdf (license.pdf) download failed!" >&2
       return 1
    fi

    # Passing arguments can cause problems with NSIS so we generate them into a separate file and include them.
    echo "; Version Definitions for Oolite" > OoliteVersions.nsh
    echo "; NOTE - This file is auto-generated by the Makefile, any manual edits will be overwritten" >> OoliteVersions.nsh
    echo "!define OOLITE_DIR ${oolite_dir//\//\\}" >> OoliteVersions.nsh
    echo "!define VER_GITHASH ${ver_githash}" >> OoliteVersions.nsh
    echo "!define VERSION ${ver_quad}" >> OoliteVersions.nsh
    echo "!define VER_FULL ${ver_full}" >> OoliteVersions.nsh
    echo "!define BUILDTIME \"${buildtime}\"" >> OoliteVersions.nsh
    echo "!define BUILDHOST_IS64BIT 1" >> OoliteVersions.nsh

    if [[ "$build_type" == "deployment" ]]; then
        echo "!define DEPLOYMENT_RELEASE 1" >> OoliteVersions.nsh
    elif [[ "$build_type" == "dev" ]]; then
        echo "!define DEV_RELEASE 1" >> OoliteVersions.nsh
    fi

    local nsis
    if [[ -v MINGW_PREFIX ]]; then
        nsis=$MINGW_PREFIX/bin/makensis
    else
        nsis=/nsis/makensis.exe
    fi
    if ! $nsis -DOUTDIR="../" OOlite.nsi; then
        echo "❌ NSIS creation failed!" >&2
        return 1
    fi
    popd
}
