#!/bin/bash

run_script() {
    # First parameter is a suffix for the build type eg. test, dev
    SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
    pushd "$SCRIPT_DIR"

    mkdir -p ../../build/nsis
    cd ../../build/nsis
    source ../../ShellScripts/common/get_version.sh

    cp ../../installers/win32/* ./

    # Passing arguments cause problems with some versions of NSIS.
    # Because of this, we generate them into a separate file and include them.
    echo "; Version Definitions for Oolite" > OoliteVersions.nsh
    echo "; NOTE - This file is auto-generated by the Makefile, any manual edits will be overwritten" >> OoliteVersions.nsh
    echo "!define VER_MAJ ${VER_MAJ}" >> OoliteVersions.nsh
    echo "!define VER_MIN ${VER_MIN}" >> OoliteVersions.nsh
    echo "!define VER_REV ${VER_REV}" >> OoliteVersions.nsh
    echo "!define VER_GITREV ${VER_GITREV}" >> OoliteVersions.nsh
    echo "!define VER_GITHASH ${VER_GITHASH}" >> OoliteVersions.nsh
    echo "!define VERSION ${VER}" >> OoliteVersions.nsh
    echo "!define BUILDTIME \"${BUILDTIME}\"" >> OoliteVersions.nsh
    echo "!define BUILDHOST_IS64BIT 1" >> OoliteVersions.nsh

    if [[ -z "$1" ]]; then
	      echo "!define DEPLOYMENT 1" >> OoliteVersions.nsh
	  elif [[ "${1,,}" == "dev" ]]; then
	      echo "!define SNAPSHOT 1" >> OoliteVersions.nsh
    fi

    if [[ -n "$MINGW_PREFIX" ]]; then
        NSIS=$MINGW_PREFIX/bin/makensis
    else
        NSIS=/nsis/makensis.exe
    fi
    if ! $NSIS -DOUTDIR="../" OOlite.nsi; then
        echo "❌ NSIS creation failed!" >&2
        return 1
    fi
    popd
}

run_script "$@"
status=$?


# Exit only if not sourced
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    exit $status
fi

