/*
	OOPlanetData.h
	For Oolite
	
	This file was automatically generated by tools/icosmesh. Do not modify.
	
	This data may be used freely.
*/

#import "OOOpenGL.h"


#define kOOPlanetDataLevels 6


typedef struct
{
	unsigned        vertexCount;
	unsigned        faceCount;
	const GLfloat   *vertices;  // vertexCount * 3
	const GLuint    *indices;   // faceCount * 3
	const GLfloat   *texCoords; // vertexCount * 2
} OOPlanetDataLevel;


extern const OOPlanetDataLevel kPlanetData[kOOPlanetDataLevels];
