/*
	OOPlanetData.c
	For Oolite
	
	This file was automatically generated by tools/icosmesh. Do not modify.
	
	This data may be used freely.
*/

#include "OOPlanetData.h"


static const GLfloat kLevel0Vertices[60] =
{
	+0.00000000f, +1.00000000f, +0.00000000f /* Magnitude: 1 */,
	+0.89442718f, +0.44721359f, +0.00000000f /* Magnitude: 1 */,
	+0.27639320f, +0.44721359f, +0.85065079f /* Magnitude: 1 */,
	-0.72360682f, +0.44721359f, +0.52573115f /* Magnitude: 1 */,
	-0.72360682f, +0.44721359f, -0.52573115f /* Magnitude: 1 */,
	+0.27639320f, +0.44721359f, -0.85065079f /* Magnitude: 1 */,
	+0.72360682f, -0.44721359f, +0.52573115f /* Magnitude: 1 */,
	-0.27639320f, -0.44721359f, +0.85065079f /* Magnitude: 1 */,
	-0.89442718f, -0.44721359f, +0.00000000f /* Magnitude: 1 */,
	-0.27639320f, -0.44721359f, -0.85065079f /* Magnitude: 1 */,
	+0.72360682f, -0.44721359f, -0.52573115f /* Magnitude: 1 */,
	+0.00000000f, -1.00000000f, +0.00000000f /* Magnitude: 1 */,
	+0.00000000f, +1.00000000f, +0.00000000f /* Magnitude: 1 */,
	+0.00000000f, +1.00000000f, +0.00000000f /* Magnitude: 1 */,
	+0.00000000f, +1.00000000f, +0.00000000f /* Magnitude: 1 */,
	+0.00000000f, +1.00000000f, +0.00000000f /* Magnitude: 1 */,
	+0.00000000f, -1.00000000f, +0.00000000f /* Magnitude: 1 */,
	+0.00000000f, -1.00000000f, +0.00000000f /* Magnitude: 1 */,
	+0.00000000f, -1.00000000f, +0.00000000f /* Magnitude: 1 */,
	+0.00000000f, -1.00000000f, +0.00000000f /* Magnitude: 1 */
};

static const GLfloat kLevel0TexCoords[40] =
{
	+0.25000000f, +0.00000000f,
	+0.25000000f, +0.35241637f,
	+0.05000000f, +0.35241637f,
	+0.84999996f, +0.35241640f,
	+0.65000004f, +0.35241640f,
	+0.44999999f, +0.35241637f,
	+0.15000001f, +0.64758360f,
	+0.94999999f, +0.64758360f,
	+0.75000000f, +0.64758360f,
	+0.55000001f, +0.64758360f,
	+0.34999999f, +0.64758360f,
	+0.50000000f, +1.00000000f,
	+0.25000000f, +0.00000000f,
	+0.25000000f, +0.00000000f,
	+0.25000000f, +0.00000000f,
	+0.25000000f, +0.00000000f,
	+0.50000000f, +1.00000000f,
	+0.50000000f, +1.00000000f,
	+0.50000000f, +1.00000000f,
	+0.50000000f, +1.00000000f
};

static const GLuint kLevel0Indices[60] =
{
	   0,    1,    2,
	  12,    2,    3,
	  13,    3,    4,
	  14,    4,    5,
	  15,    5,    1,
	  11,    6,    7,
	  16,    7,    8,
	  17,    8,    9,
	  18,    9,   10,
	  19,   10,    6,
	   1,    2,    6,
	   2,    3,    7,
	   3,    4,    8,
	   4,    5,    9,
	   5,    1,   10,
	   6,    7,    2,
	   7,    8,    3,
	   8,    9,    4,
	   9,   10,    5,
	  10,    6,    1
};


#define kLevel1Vertices 0
#define kLevel1TexCoords 0
#define kLevel1Indices 0
#define kLevel2Vertices 0
#define kLevel2TexCoords 0
#define kLevel2Indices 0
#define kLevel3Vertices 0
#define kLevel3TexCoords 0
#define kLevel3Indices 0
#define kLevel4Vertices 0
#define kLevel4TexCoords 0
#define kLevel4Indices 0
#define kLevel5Vertices 0
#define kLevel5TexCoords 0
#define kLevel5Indices 0


const OOPlanetDataLevel kPlanetData[kOOPlanetDataLevels] =
{
	{ 20, 20, kLevel0Vertices, kLevel0Indices, kLevel0TexCoords },
	{ 20, 20, kLevel1Vertices, kLevel1Indices, kLevel1TexCoords },
	{ 20, 20, kLevel2Vertices, kLevel2Indices, kLevel2TexCoords },
	{ 20, 20, kLevel3Vertices, kLevel3Indices, kLevel3TexCoords },
	{ 20, 20, kLevel4Vertices, kLevel4Indices, kLevel4TexCoords },
	{ 20, 20, kLevel5Vertices, kLevel5Indices, kLevel5TexCoords }
};
