ifeq ($(profile),yes)
    ADDITIONAL_CFLAGS            += -g -pg
    ADDITIONAL_OBJCFLAGS         += -g -pg
endif
ifeq ($(debug),yes)
    ADDITIONAL_CFLAGS            += -g -O0
    ADDITIONAL_OBJCFLAGS         += -g -O0
    GNUSTEP_OBJ_DIR_NAME         := $(GNUSTEP_OBJ_DIR_NAME).dbg
    ADDITIONAL_CFLAGS            += -DDEBUG -DOO_DEBUG -DOO_CHECK_GL_HEAVY=1
    ADDITIONAL_OBJCFLAGS         += -DDEBUG -DOO_DEBUG -DOO_CHECK_GL_HEAVY=1
endif

# these are common settings for both test and deployment release configurations
ifeq ($(NO_SHADERS),yes)
    ADDITIONAL_CFLAGS            += -DNO_SHADERS=1
    ADDITIONAL_OBJCFLAGS         += -DNO_SHADERS=1
endif

# DEPLOYMENT_RELEASE_CONFIGURATION value is passed from Makefile. Note that the deployment release settings
# are forced, while test release settings are adjustable.
ifeq ($(DEPLOYMENT_RELEASE_CONFIGURATION),yes)
    ADDITIONAL_CFLAGS            += -DNDEBUG
    ADDITIONAL_OBJCFLAGS         += -DNDEBUG
    ADDITIONAL_CFLAGS            += -DOO_CHECK_GL_HEAVY=0
    ADDITIONAL_OBJCFLAGS         += -DOO_CHECK_GL_HEAVY=0
    ADDITIONAL_CFLAGS            += -DOO_EXCLUDE_DEBUG_SUPPORT=1
    ADDITIONAL_OBJCFLAGS         += -DOO_EXCLUDE_DEBUG_SUPPORT=1
    ADDITIONAL_CFLAGS            += -DOO_OXP_VERIFIER_ENABLED=0
    ADDITIONAL_OBJCFLAGS         += -DOO_OXP_VERIFIER_ENABLED=0
    ADDITIONAL_CFLAGS            += -DOO_LOCALIZATION_TOOLS=0
    ADDITIONAL_OBJCFLAGS         += -DOO_LOCALIZATION_TOOLS=0
    ADDITIONAL_CFLAGS            += -DDEBUG_GRAPHVIZ=0
    ADDITIONAL_OBJCFLAGS         += -DDEBUG_GRAPHVIZ=0
    ADDITIONAL_CFLAGS            += -DOO_FOV_INFLIGHT_CONTROL_ENABLED=0
    ADDITIONAL_OBJCFLAGS         += -DOO_FOV_INFLIGHT_CONTROL_ENABLEDD=0
else
    ifeq ($(BUILD_WITH_DEBUG_FUNCTIONALITY),no)
        ADDITIONAL_CFLAGS        += -DNDEBUG
        ADDITIONAL_OBJCFLAGS     += -DNDEBUG
    endif
    ifeq ($(OO_CHECK_GL_HEAVY),yes)
        ADDITIONAL_CFLAGS        += -DOO_CHECK_GL_HEAVY=1
        ADDITIONAL_OBJCFLAGS     += -DOO_CHECK_GL_HEAVY=1
    endif
    ifeq ($(OO_EXCLUDE_DEBUG_SUPPORT),yes)
        ADDITIONAL_CFLAGS        += -DOO_EXCLUDE_DEBUG_SUPPORT=1
        ADDITIONAL_OBJCFLAGS     += -DOO_EXCLUDE_DEBUG_SUPPORT=1
    endif
    ifeq ($(OO_OXP_VERIFIER_ENABLED),yes)
        ADDITIONAL_CFLAGS        += -DOO_OXP_VERIFIER_ENABLED=1
        ADDITIONAL_OBJCFLAGS     += -DOO_OXP_VERIFIER_ENABLED=1
    endif
    ifeq ($(OO_LOCALIZATION_TOOLS),yes)
        ADDITIONAL_CFLAGS        += -DOO_LOCALIZATION_TOOLS=1
        ADDITIONAL_OBJCFLAGS     += -DOO_LOCALIZATION_TOOLS=1
    endif
    ifeq ($(DEBUG_GRAPHVIZ),yes)
        ADDITIONAL_CFLAGS        += -DDEBUG_GRAPHVIZ=1
        ADDITIONAL_OBJCFLAGS     += -DDEBUG_GRAPHVIZ=1
    endif
    ifeq ($(OO_FOV_INFLIGHT_CONTROL_ENABLED),yes)
        ADDITIONAL_CFLAGS        += -DOO_FOV_INFLIGHT_CONTROL_ENABLED=1
        ADDITIONAL_OBJCFLAGS     += -DOO_FOV_INFLIGHT_CONTROL_ENABLED=1
    endif
endif

ifeq ($(SNAPSHOT_BUILD), yes)
    ADDITIONAL_CFLAGS            += -DSNAPSHOT_BUILD -DOOLITE_SNAPSHOT_VERSION=\"$(VERSION_STRING)\"
    ADDITIONAL_OBJCFLAGS         += -DSNAPSHOT_BUILD -DOOLITE_SNAPSHOT_VERSION=\"$(VERSION_STRING)\"
endif
