.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH OOLITE 6 "March 6th, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac

.SH NAME
Oolite \- a space-sim game
.SH SYNOPSIS
.B oolite
.br
.SH DESCRIPTION
This manual page briefly documents \fBOolite\fP.
.PP
\fBOolite\fP is a reinterpretation of the 8-bit classic space
shooter/trading game \fBElite\fP, which was written by Ian Bell and David
Braben.
.br 2
.SH FAQ
.PP
.B What is the purpose of the game?
.br
To fly from planet to planet, buying and selling goods, shooting pirates
or committing acts of piracy.
There's no goal other than perhaps to achieve the rank of \fBELITE\fP.
.br
.PP
.B How do I quit?
.br
While docked, use the 'F2' key. When in flight, use the 'p' key.
.br
.PP
.B I'm still confused, how do I play?
.br
Documentation can be found in the \fI/usr/share/doc/oolite\fP directory.
You should start with \fBREADME.TXT.gz\fP for window settings.
Then, the \fBPLAYING.TXT.gz\fP document gives a basic overview of the
controls.
.br
For a full description of all controls, please see the "Oolite Reference
Sheet" (\fBOoliteRS.pdf\fP) which is suitable for printing out.
.br
.PP
.B Where can I find more information?
.br
For the nostalgic, Ian Bell's "Space Traders Flight Training Manual" for
the original BBC Elite is still a very good introduction to the game and
can be found
.URL http://home.clara.net/iancgbell/elite/manual.htm "online" "."
.br
A large amount of additional information, including advice for newcomers,
\fBO\fPolite E\fBx\fPpansion \fBP\fPacks (OXP), the Elite/Oolite wiki, and
the Oolite Bulletin Board is linked from
.URL http://www.oolite.org/ "the Oolite home page" "."
.PP
.TP
.B What do the various colors represent on the radar?
.br
\(bu White - unpowered items that can't mass-lock the in-system drive.
.br
\(bu Green/Yellow - navigation buoys.
.br
\(bu Yellow - powered craft.
.br
\(bu Red - powered craft identified as hostile.
.br
\(bu Green - space stations.
.br
\(bu Green/Red - thargoids
.br
\(bu Purple - police
.br
\(bu Blue/Red - police on intercept
.br
\(bu Red/Yellow - active mine (about to detonate)
.br
.mso www.tmac
.SH AUTHOR
Oolite was written by Giles Williams and others, and it was ported to the
GNU/Linux operating system by the Oolite Linux project.
The original version can be found at
.URL http://www.oolite.org/ "the Oolite home page" "."
.PP
This manual page was written by Eddy Petrisor <eddy.petrisor@gmail.com>,
for the Debian project and updated by various maintainers,
(but may be used by others).
