oolite.app/Resources/AIs                            usr/lib/GNUstep/Applications/oolite.app/Resources
oolite.app/Resources/Config                         usr/lib/GNUstep/Applications/oolite.app/Resources
oolite.app/Resources/Images                         usr/lib/GNUstep/Applications/oolite.app/Resources
oolite.app/Resources/Info-gnustep.plist             usr/lib/GNUstep/Applications/oolite.app/Resources
oolite.app/Resources/InfoPlist.strings              usr/lib/GNUstep/Applications/oolite.app/Resources
oolite.app/Resources/Models                         usr/lib/GNUstep/Applications/oolite.app/Resources
oolite.app/Resources/Music                          usr/lib/GNUstep/Applications/oolite.app/Resources
oolite.app/Resources/oolite-document.icns           usr/lib/GNUstep/Applications/oolite.app/Resources
oolite.app/Resources/oolite-expansion-document.icns usr/lib/GNUstep/Applications/oolite.app/Resources
oolite.app/Resources/oolite-icon.icns               usr/lib/GNUstep/Applications/oolite.app/Resources
oolite.app/Resources/Scripts                        usr/lib/GNUstep/Applications/oolite.app/Resources
oolite.app/Resources/Shaders                        usr/lib/GNUstep/Applications/oolite.app/Resources
oolite.app/Resources/Sounds                         usr/lib/GNUstep/Applications/oolite.app/Resources
oolite.app/Resources/Textures                       usr/lib/GNUstep/Applications/oolite.app/Resources
oolite.app/Resources/Schemata                       usr/lib/GNUstep/Applications/oolite.app/Resources

deps/Cross-platform-deps/DTDs                       usr/lib/GNUstep/Library
