/*
	OOPlanetData.h
	For Oolite
	
	This file was automatically generated by tools/icosmesh. Do not modify.
	
	This data may be used freely.
*/

#include "OOOpenGLOnly.h"


#define kOOPlanetDataLevels 6


typedef struct
{
	unsigned        vertexCount;
	unsigned        faceCount;
	GLenum          type;
	const void      *indices;   // faceCount * 3
} OOPlanetDataLevel;


extern const OOPlanetDataLevel kPlanetData[kOOPlanetDataLevels];


#define kOOPlanetDataVertexCount 10446

extern const GLfloat kOOPlanetVertices[kOOPlanetDataVertexCount * 3];
extern const GLfloat kOOPlanetTexCoords[kOOPlanetDataVertexCount * 2];
