version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - doxygen
    - graphviz
  jobs:
    pre_build:
      - ./Documentation/documentation_prebuild.sh

mkdocs:
  configuration: build/documentation/mkdocs.yaml

python:
  install:
    - requirements: ./Documentation/requirements.txt