version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - doxygen
    - graphviz
    - libreoffice
  jobs:
    pre_build:
      - python3 -m playwright install chromium
      - ./Documentation/build_doxygen.sh
      - ./Documentation/build_referencesheet.sh

mkdocs:
  configuration: build/documentation/mkdocs.yaml

python:
  install:
    - requirements: ./Documentation/requirements.txt
