name: build-mac

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: run build
        run: |
          find .
          swift build
      - name: run tests
        run: |
          find .
          swift text
