name: build-mac

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Oolite
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Checkout libpng
        uses: actions/checkout@v2
        with:
          repository: glennrp/libpng
          path: deps/libpng
          submodules: true

      - name: check environment
        run: |
          xcodebuild -list -workspace Oolite.xcodeproj/project.xcworkspace
          xcodebuild -list -project Oolite.xcodeproj
          echo "Variables:"
          env | sort
          echo "Current directory:"
          pwd
          echo "Filesystem:"
          find .

      - name: run build
        run: |
          xcodebuild -configuration "TestRelease" MACOSX_DEPLOYMENT_TARGET=10.9 OTHER_CFLAGS="-Wno-deprecated-declarations"
#          xcodebuild -scheme 'Oolite - Test Release' build

#      - name: run tests
#        run: |
#          xcodebuild test -scheme 'Oolite - Test Release' -destination target/tests

      - name: where is the release?
        run: |
          find .

      - name: Create Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Oolite MacOS Nightly"
          files: |
            build/TestRelease
