name: build-mac

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: check environment
        run: |
          xcodebuild -list -workspace Oolite.xcodeproj/project.xcworkspace
          xcodebuild -list -project Oolite.xcodeproj
          find .

      - name: run build
        run: |
          xcodebuild -scheme 'Oolite - Test Release' build

      - name: run tests
        run: |
          xcodebuild test -scheme 'Oolite - Test Release' -destination target/tests
