name: build-mac

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Oolite
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Checkout libpng
        uses: actions/checkout@v2
        with:
          repository: glennrp/libpng
          path: deps/libpng
          submodules: true

      - name: check environment
        run: |
          xcodebuild -list -workspace Oolite.xcodeproj/project.xcworkspace
          xcodebuild -list -project Oolite.xcodeproj
          echo "Variables:"
          env | sort
          echo "Current directory:"
          pwd
          echo "Filesystem:"
          find .

      - name: run build
        run: |
          xcodebuild -scheme 'Oolite - Test Release' build
#          xcodebuild -configuration "TestRelease" MACOSX_DEPLOYMENT_TARGET=10.9 OTHER_CFLAGS="-Wno-deprecated-declarations"

#      - name: run tests
#        run: |
#          xcodebuild test -scheme 'Oolite - Test Release' -destination target/tests

      - name: Create Release
        run: |
          #!/bin/bash -x
          echo "create dest folder"
          mkdir -p release/TestRelease
          echo "copy Oolite.app"
          cp -rv build/TestRelease/Oolite.app release/TestRelease || echo "cp Oolite.app failed with $?"
          mkdir "create Documentation folder"
          mkdir -p release/TestRelease/Documentation
          echo "copy documents..."
          cp -v Doc/AdviceForNewCommanders.doc release/TestRelease/Documentation
          cp -v Doc/contributors.txt release/TestRelease/Documentation
          cp -v Doc/GPL.TXT release/TestRelease/Documentation
          cp -v Doc/LICENSE.TXT release/TestRelease/Documentation
          cp -v Doc/OoliteReadMe.pdf release/TestRelease/Documentation
          cp -v Doc/OoliteRS.pdf release/TestRelease/Documentation
          echo "create Extras folder"
          mkdir -p release/TestRelease/Extras
          echo "copy extras"
          cp -v -r tools/BBC\ keys release/TestRelease/Extras
          echo "building ZIP archive"
          cd release; zip --recurse-paths TestRelease.zip TestRelease

      - name: Publish Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Oolite MacOS Nightly"
          files: |
            release/TestRelease.zip
